[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 'z'
panic = 'abort'

[workspace]
members = [
  "crates/cli",
  "crates/languages",
  "crates/macros",
  "crates/server",
  "crates/syntax",
  "xtask",
]
default-members = ["crates/cli"]
